### ISSUE TITLE
Assertion Failing

### ISSUE THREAD

**Issue by MongerBeep** [Damianonymous/MFCRecorder#2]
The assertion at Model.js, line 419, is failing. Apparently MFC is now including some non object information in the sites object.

Commenting out the assertion seems to have fixed the problem, but it is rather inelegant.

**Comment by Damianonymous** [comment]
Despite the changes in the MFC code, the application seems to continue to work without major problems. Unfortunately, I am unable to update it, and the author's subject on reddit has been archived, and direct contact via private message remains.

https://www.reddit.com/r/DataHoarder/comments/6eixan/scripts_for_automating_the_recording_of_multiple/
