### ISSUE TITLE
using capitals in the completed_directory

### ISSUE THREAD

**Issue by wylde780** [Damianonymous/MFCRecorder#4]
First off thanks for sharing. 

the destination gets converted to lowercase and does not matter if you use the full path. I am trying to find where this is occurring in the py but it is not obvious to me. 

using Python 3.6.7
example config.conf 
completed_directory = ../MFC_Captures

items will be moved to ../mfc_captures

**Comment by Damianonymous** [comment]
I guess you're using Windows that is not case-sensitive, in files and folders?

**Comment by wylde780** [comment]
actually, I'm using Ubuntu to be specific 18.04

**Comment by Damianonymous** [comment]
It's hard for me to answer, I'm not a programmer, I only provide applications from my archive ;)
